### ISSUE TITLE
Lot of logs being printed on the console.

### ISSUE THREAD

**Issue by suchitrak** [olivierwilkinson/webdriverio-testing-library#12]
The library is cool. But I see a lot of Logs like this is printed on the console. when I tried to use the method browser.findByRole. Is there any way I could avoid that ?

     class="SelectorDropdown"
                    >
                      <div
                        class="quick-search-selector"
                      >
                        <input
                          aria-autocomplete="list"
                          aria-expanded="false"
                          aria-label="Search Files and Folders"
                          autocomplete="off"
                          class="search-input search-input"
                          data-resin-target="searchbar"
                          name="query"
                          placeholder="Search Files and Folders"
                          role="combobox"
                          type="text"
                          value=""
                        />
                      </div>
                    class="action-buttons"
                    <button
                      aria-label="Search Options"
                      class="btn-plain action-button"
                      data-resin-target="showkeywordless"
                      tabindex="0"
                      type="button"
                      <span
                        class="btn-content"
                        <svg
                          focusable="false"
                          height="16"
                          role="presentation"
                          viewBox="0 0 16 16"
                          width="16"
                        >
                          <path
                            d="M8.83 12a2.995 2.995 0 000-2H15a1 1 0 010 2H8.83zm-5.66 0H1a1 1 0 010-2h2.17a2.995 2.995 0 000 2zm10.66-6a2.995 2.995 0 000-2H15a1 1 0 010 2h-1.17zM8.17 6H1a1 1 0 110-2h7.17a2.995 2.995 0 000 2zM9 5a2 2 0 114 0 2 2 0 01-4 0zm-5 6a2 2 0 114 0 2 2 0 01-4 0z"
                            fill="#909090"
                            fill-rule="evenodd"
                          />
                        </svg>
                          class="mls"
                          height="8"

**Comment by olivierwilkinson** [comment]
Hi there 👋 

Do you mean when the element is not found? The current behaviour is to send back the error from dom-testing-library, which includes a log of the document. It's true that possibly that isn't as helpful here and maybe we should include an option to strip that part of the error log.

If that is not what you are refering to there are logs that come from WebdriverIO that can be silenced, we use `logLevel: 'silent'` in our wdio.conf.js file to reduce the output.

**Comment by suchitrak** [comment]
Yeah I think I will probably try using  logLevel: 'silent'. But then I wont be able to see other logs from webdriverio. The logs do appear even when element is found and there is no error at all.

**Comment by olivierwilkinson** [comment]
Just spent a little time looking into this more thoroughly and It should be possible to set the logLevel to 'warn' without seeing logs for expected errors.

There was a legitimate bug I found which caused errors thrown by getBy queries to be logged by WebdriverIO even if they were caught in the test. I'm not sure it's what you are seeing because it shouldn't have affected findBy queries but it's possible. [I've raised a PR](https://github.com/testing-library/webdriverio-testing-library/pull/13) which fixes the bug and changes the log level we are using in our tests to 'warn' 👍.

**Comment by olivierwilkinson** [comment]
I've released the fix to the bug I found in [v3.0.0](https://github.com/testing-library/webdriverio-testing-library/pull/13#issuecomment-859970228), let me know if you are able to set the logLevel to 'warn' happily with the new version 😄. I'll keep this open until I know that was the issue.

**Comment by suchitrak** [comment]
Yes I don't see so many  logs of the document when I set the log level to warn.
