### ISSUE TITLE
The library doesn't seem to be working with firefox

### ISSUE THREAD

**Issue by suchitrak** [olivierwilkinson/webdriverio-testing-library#18]
I see the same issue as stated here:
https://github.com/testing-library/nightwatch-testing-library/issues/31

[0-1] 2021-06-14T16:45:13.502Z ERROR webdriver: Request failed with status 500 due to javascript error: TypeError: window.TestingLibraryDom is undefined

**Comment by olivierwilkinson** [comment]
Thanks for raising this!

Just wanted to let you know that I'm working on this, I've got it running on Firefox successfully but there are other issues with the RegExp deserialisation (it seems)

I'll raise a PR once I've fixed that and have updated the test setup to include firefox so we can make sure this doesn't happen in future. 👍

**Comment by suchitrak** [comment]
Thanks for the quick response.

**Comment by olivierwilkinson** [comment]
@suchitrak everything is working for me now 🥳. Please don't hestitate to let me know if you are still having issues with Firefox!

**Comment by suchitrak** [comment]
Great! Thanks. I will try that today.

**Comment by suchitrak** [comment]
Works on my end too. Thanks @olivierwilkinson

**Comment by olivierwilkinson** [comment]
No worries at all, thanks for raising it 😄
