### ISSUE TITLE
The library throws error when executing tests on Internet Explorer

### ISSUE THREAD

**Issue by suchitrak** [olivierwilkinson/webdriverio-testing-library#19]
When following line is executed on IE11, Below error is displayed. The below lines works perfectly on Chrome and Chromium Edge though. I am using webdriverio version V6. 

```
When('I {word} the/a(n) {word} named/called/labelled/labeled {string}', (action, ariaRole, text) => {
    browser.findByRole(ariaRole, { name: text })[action]();
});

[0-1] 2021-06-14T18:23:16.301Z ERROR webdriver: Request failed with status 500 due to javascript error: Error executing JavaScript
```

**Comment by olivierwilkinson** [comment]
We currently use a target of es2019 which is too recent to support IE 11. When I get some more time I'll look into getting the target to ES5 which does support IE 11 but it's not a simple as just changing it in the tsconfig unfortunately.

I'll look into it after I've got Firefox working properly, but if you'd like to raise a PR it would be more than welcome!

**Comment by dmccr** [comment]
I'm seeing the same error on firefox (using latest version on browserstack)
`WARN webdriver: Request failed with status 500 due to TypeError: window.TestingLibraryDom is undefined`

**Comment by olivierwilkinson** [comment]
> I'm seeing the same error on firefox (using latest version on browserstack)
> `WARN webdriver: Request failed with status 500 due to TypeError: window.TestingLibraryDom is undefined`

Hi there @dmccr 👋 .

Oh bummer, I thought I had fixed that issue in [v3.0.2](https://github.com/testing-library/webdriverio-testing-library/releases/tag/v3.0.2)! Would you mind confirming that you are on that version? Then I'll reopen [this issue](https://github.com/testing-library/webdriverio-testing-library/issues/18).

I made sure to start running our tests against the latest version of Firefox when I originally resolved that issue so if possible would you be able to let me know what device and version of Firefox Browserstack is using when it fails? The problem might be device / environment specific.

Thanks for letting us know btw 😄

**Comment by dmccr** [comment]
@olivierwilkinson Thanks for the quick response.
Indeed I was using older version 2.1.1, and its working fine on 3.0.2.  Should have checked that :(
I'm a big fan of testing-library approach.  Keep up the good work!

**Comment by nickserv** [comment]
This seems to have been fixed, and Internet Explorer's support is ending anyway.
