### ISSUE TITLE
Compatibility with v8 of WebdriverIO

### ISSUE THREAD

**Issue by christian-bromann** [olivierwilkinson/webdriverio-testing-library#42]
Hey 👋 

just wanted to let you know about a breaking change with the upcoming `v8` release. In there we remove all `browser` commands from element scopes. This breaks in `injectDOMTestingLibrary` where `container` is an element (with selector `'body'`). I suggest to call execute as follows `container.parent.execute(...)` to run the command from the browser scope. This would already work with today `v7` and prior versions.

Happy to provide a PR if needed.

**Comment by olivierwilkinson** [comment]
Hi there,

Thank you for the heads up and the PR! I'll have a look at it as soon as I am able 😁
