### ISSUE TITLE
TypeError: container.parent.execute is not a function

### ISSUE THREAD

**Issue by segovia** [olivierwilkinson/webdriverio-testing-library#46]
The error in the title "TypeError: container.parent.execute is not a function" happens with webdriverio v8 when you use a testing library query nested within another element.

I believe this issue is related to the fix done for: https://github.com/testing-library/webdriverio-testing-library/issues/42

I have a proposed solution that I will link in the comments.

**Comment by segovia** [comment]
Here is the pull request. You are free to edit the commit. The naming might be sub-optimal.

https://github.com/testing-library/webdriverio-testing-library/pull/47

**Comment by olivierwilkinson** [comment]
@segovia Thank you very much for raising this! I'll have a look at your PR as soon as I get the chance 🙌

**Comment by segovia** [comment]
Since the code was merged, do we have a release in sight?

**Comment by olivierwilkinson** [comment]
> Since the code was merged, do we have a release in sight?

Yup! Sorry I was looking to release and got caught up fixing the builds again.

**Comment by olivierwilkinson** [comment]
@segovia this has just been released, sorry for the delay! You should be able to use v3.2.1 now 😄

**Comment by segovia** [comment]
That's awesome! Thanks!
